
format_version: 3
pipelines:
  meh:
    group: meh
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 1
    materials:
      git:
        git: https://github.com/gocd-demo/node-bulletin-board.git
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
    - build_and_publish_image:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          BuildJob:
            timeout: 0
            tasks:
            - exec:
                command: echo "sample"
run_if: passed        
